version: '2'
services:
  eureka-server:
    image: lahirusandaruwan/discovery-service:2.0
    ports:
      - "8761:8761"

  config-server:
    image: lahirusandaruwan/spring-cloud-config-server:1.0
    ports:
      - "8888:8888"

  eod-engine:
    image: lahirusandaruwan/eod-engine-consumer:4.0
    # ... other environment variables
    ports:
      - "8070:8070"
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
    depends_on:
      - config-server
    links:
      - config-server

  api-cloud-gateway:
    image: gateway-service:5.0
    # ... other environment variables
    ports:
      - "8989:8989"
    restart: unless-stopped
    environment:
      #      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    links:
      - eureka-server

  eod-dashboard:
    image: dashboard-service:2.0
    # ... other environment variables
    ports:
      - "7778:7778"
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka
    depends_on:
      - config-server
      - eureka-server
    links:
      - config-server
      - eureka-server

  producer:
    image: producer:1.0
    ports:
      - "8055:8055"
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka
    depends_on:
      - config-server
      - eureka-server

  web-socket:
    image: web-socket-service:1.0
    ports:
      - "7777:7777"

  file-processing-engine:
    image: eod-file_processing-producer:1.0
    ports:
      - "8065:8065"
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka
    depends_on:
      - config-server
      - eureka-server

  file-generation-engine:
    image: eod-file_generation-producer:1.0
    ports:
      - "7788:7788"
    restart: unless-stopped
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://192.168.1.122:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka
    depends_on:
      - config-server
      - eureka-server




