spring:
  application:
    name: GatewayService
#  boot:
#    admin:
#      client:
#        instance:
#          management-base-url: http://localhost:8081
  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: DashboardService
          uri: lb://DashboardService
          predicates:
            - Path=/eod-dashboard/**
          filters:
            - AuthenticationFilter

        - id: EODEngineProducer
          uri: lb://EODEngineProducer
          predicates:
            - Path=/eod-engine/**
          filters:
            - AuthenticationFilter

        - id: EODFileGenProducer
          uri: lb://EODFileGenProducer
          predicates:
            - Path=/eod-file-generation/**
          filters:
            - AuthenticationFilter

        - id: EODFileProcessingProducer
          uri: lb://EODFileProcessingProducer
          predicates:
            - Path=/eod-file-processing-engine/**
          filters:
            - AuthenticationFilter

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    instanceId: GatewayService:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    ip-address: ${HERE-GOES-YOUR-PUBLIC-IP:192.168.1.122}


# Ribbon config
ribbon:
  eureka:
    enabled: true
server:
  port: 8989