spring:
  application:
    name: GatewayService
#  profiles:
#    active: qa
  cloud:
    gateway:
      defaultFilters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: DashboardService
          uri: lb://DashboardService
          predicates:
            - Path=/eod-dashboard/**
          filters:
            - AuthenticationFilter

        - id: EODEngineProducer
          uri: lb://EODEngineProducer
          predicates:
            - Path=/eod-engine/**
          filters:
            - AuthenticationFilter

        - id: EODFileGenProducer
          uri: lb://EODFileGenProducer
          predicates:
            - Path=/eod-file-generation/**
          filters:
            - AuthenticationFilter

        - id: EODFileProcessingProducer
          uri: lb://EODFileProcessingProducer
          predicates:
            - Path=/eod-file-processing-engine/**
          filters:
            - AuthenticationFilter

#        - id: swagger
#          predicates:
#            - Path=/product-dashboard-docs/**
#          filters:
#            - RewritePath=/product-dashboard-docs/(?<path>.*), /$\{path}/product-dashboard-docs
#          uri: http://localhost:${server.port}

# Eureka config
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    instanceId: GatewayService:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
#    ip-address: ${HERE-GOES-YOUR-PUBLIC-IP:192.168.1.122}


# Ribbon config
ribbon:
  eureka:
    enabled: true
server:
  port: 8989

  servlet:
    context-path: /

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /DashboardService/v3/api-docs
        name: Dashboard Service
        primaryName: Dashboard Service

#springdoc:
#  api-docs:
#    path: /GatewayService/v3/api-docs
#  swagger-ui:
#    path: /GatewayService/swagger-ui.html
